# Generated by Django 5.2.5 on 2025-09-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_appuser_email_appuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('so', 'Somali'), ('ar', 'Arabic')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='appuser',
            name='region',
            field=models.CharField(choices=[('Mogadishu', 'Mogadishu'), ('Bay', 'Bay'), ('Hargeisa', 'Hargeisa'), ('Gedo', 'Gedo')], default='Mogadishu', max_length=50),
        ),
    ]
